// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/legal_engine.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Clause struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	ClauseType    string                 `protobuf:"bytes,3,opt,name=clause_type,json=clauseType,proto3" json:"clause_type,omitempty"`
	ClauseText    string                 `protobuf:"bytes,4,opt,name=clause_text,json=clauseText,proto3" json:"clause_text,omitempty"`
	RiskLevel     string                 `protobuf:"bytes,5,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`
	RiskReasoning string                 `protobuf:"bytes,6,opt,name=risk_reasoning,json=riskReasoning,proto3" json:"risk_reasoning,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Clause) Reset() {
	*x = Clause{}
	mi := &file_proto_legal_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Clause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Clause) ProtoMessage() {}

func (x *Clause) ProtoReflect() protoreflect.Message {
	mi := &file_proto_legal_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Clause.ProtoReflect.Descriptor instead.
func (*Clause) Descriptor() ([]byte, []int) {
	return file_proto_legal_engine_proto_rawDescGZIP(), []int{0}
}

func (x *Clause) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Clause) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *Clause) GetClauseType() string {
	if x != nil {
		return x.ClauseType
	}
	return ""
}

func (x *Clause) GetClauseText() string {
	if x != nil {
		return x.ClauseText
	}
	return ""
}

func (x *Clause) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *Clause) GetRiskReasoning() string {
	if x != nil {
		return x.RiskReasoning
	}
	return ""
}

func (x *Clause) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type AnalyzeDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeDocumentRequest) Reset() {
	*x = AnalyzeDocumentRequest{}
	mi := &file_proto_legal_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeDocumentRequest) ProtoMessage() {}

func (x *AnalyzeDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_legal_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeDocumentRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeDocumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_legal_engine_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *AnalyzeDocumentRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type AnalyzeDocumentResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	DocumentId            string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	DocumentRiskLevel     string                 `protobuf:"bytes,2,opt,name=document_risk_level,json=documentRiskLevel,proto3" json:"document_risk_level,omitempty"`
	DocumentRiskReasoning string                 `protobuf:"bytes,3,opt,name=document_risk_reasoning,json=documentRiskReasoning,proto3" json:"document_risk_reasoning,omitempty"`
	Clauses               []*Clause              `protobuf:"bytes,4,rep,name=clauses,proto3" json:"clauses,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AnalyzeDocumentResponse) Reset() {
	*x = AnalyzeDocumentResponse{}
	mi := &file_proto_legal_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeDocumentResponse) ProtoMessage() {}

func (x *AnalyzeDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_legal_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeDocumentResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeDocumentResponse) Descriptor() ([]byte, []int) {
	return file_proto_legal_engine_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyzeDocumentResponse) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *AnalyzeDocumentResponse) GetDocumentRiskLevel() string {
	if x != nil {
		return x.DocumentRiskLevel
	}
	return ""
}

func (x *AnalyzeDocumentResponse) GetDocumentRiskReasoning() string {
	if x != nil {
		return x.DocumentRiskReasoning
	}
	return ""
}

func (x *AnalyzeDocumentResponse) GetClauses() []*Clause {
	if x != nil {
		return x.Clauses
	}
	return nil
}

type GetClausesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClausesRequest) Reset() {
	*x = GetClausesRequest{}
	mi := &file_proto_legal_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClausesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClausesRequest) ProtoMessage() {}

func (x *GetClausesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_legal_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClausesRequest.ProtoReflect.Descriptor instead.
func (*GetClausesRequest) Descriptor() ([]byte, []int) {
	return file_proto_legal_engine_proto_rawDescGZIP(), []int{3}
}

func (x *GetClausesRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type GetClausesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clauses       []*Clause              `protobuf:"bytes,1,rep,name=clauses,proto3" json:"clauses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClausesResponse) Reset() {
	*x = GetClausesResponse{}
	mi := &file_proto_legal_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClausesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClausesResponse) ProtoMessage() {}

func (x *GetClausesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_legal_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClausesResponse.ProtoReflect.Descriptor instead.
func (*GetClausesResponse) Descriptor() ([]byte, []int) {
	return file_proto_legal_engine_proto_rawDescGZIP(), []int{4}
}

func (x *GetClausesResponse) GetClauses() []*Clause {
	if x != nil {
		return x.Clauses
	}
	return nil
}

type ExtractMandatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegulationId  string                 `protobuf:"bytes,1,opt,name=regulation_id,json=regulationId,proto3" json:"regulation_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractMandatesRequest) Reset() {
	*x = ExtractMandatesRequest{}
	mi := &file_proto_legal_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractMandatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractMandatesRequest) ProtoMessage() {}

func (x *ExtractMandatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_legal_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractMandatesRequest.ProtoReflect.Descriptor instead.
func (*ExtractMandatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_legal_engine_proto_rawDescGZIP(), []int{5}
}

func (x *ExtractMandatesRequest) GetRegulationId() string {
	if x != nil {
		return x.RegulationId
	}
	return ""
}

func (x *ExtractMandatesRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ExtractMandatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mandates      []string               `protobuf:"bytes,1,rep,name=mandates,proto3" json:"mandates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractMandatesResponse) Reset() {
	*x = ExtractMandatesResponse{}
	mi := &file_proto_legal_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractMandatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractMandatesResponse) ProtoMessage() {}

func (x *ExtractMandatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_legal_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractMandatesResponse.ProtoReflect.Descriptor instead.
func (*ExtractMandatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_legal_engine_proto_rawDescGZIP(), []int{6}
}

func (x *ExtractMandatesResponse) GetMandates() []string {
	if x != nil {
		return x.Mandates
	}
	return nil
}

type AnalyzeImpactRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MandateText          string                 `protobuf:"bytes,1,opt,name=mandate_text,json=mandateText,proto3" json:"mandate_text,omitempty"`
	InternalDocumentId   string                 `protobuf:"bytes,2,opt,name=internal_document_id,json=internalDocumentId,proto3" json:"internal_document_id,omitempty"`
	InternalDocumentText string                 `protobuf:"bytes,3,opt,name=internal_document_text,json=internalDocumentText,proto3" json:"internal_document_text,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AnalyzeImpactRequest) Reset() {
	*x = AnalyzeImpactRequest{}
	mi := &file_proto_legal_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeImpactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeImpactRequest) ProtoMessage() {}

func (x *AnalyzeImpactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_legal_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeImpactRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeImpactRequest) Descriptor() ([]byte, []int) {
	return file_proto_legal_engine_proto_rawDescGZIP(), []int{7}
}

func (x *AnalyzeImpactRequest) GetMandateText() string {
	if x != nil {
		return x.MandateText
	}
	return ""
}

func (x *AnalyzeImpactRequest) GetInternalDocumentId() string {
	if x != nil {
		return x.InternalDocumentId
	}
	return ""
}

func (x *AnalyzeImpactRequest) GetInternalDocumentText() string {
	if x != nil {
		return x.InternalDocumentText
	}
	return ""
}

type AnalyzeImpactResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ImpactLevel     string                 `protobuf:"bytes,1,opt,name=impact_level,json=impactLevel,proto3" json:"impact_level,omitempty"` // HIGH, MEDIUM, LOW, NONE
	ImpactReasoning string                 `protobuf:"bytes,2,opt,name=impact_reasoning,json=impactReasoning,proto3" json:"impact_reasoning,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnalyzeImpactResponse) Reset() {
	*x = AnalyzeImpactResponse{}
	mi := &file_proto_legal_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeImpactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeImpactResponse) ProtoMessage() {}

func (x *AnalyzeImpactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_legal_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeImpactResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeImpactResponse) Descriptor() ([]byte, []int) {
	return file_proto_legal_engine_proto_rawDescGZIP(), []int{8}
}

func (x *AnalyzeImpactResponse) GetImpactLevel() string {
	if x != nil {
		return x.ImpactLevel
	}
	return ""
}

func (x *AnalyzeImpactResponse) GetImpactReasoning() string {
	if x != nil {
		return x.ImpactReasoning
	}
	return ""
}

var File_proto_legal_engine_proto protoreflect.FileDescriptor

const file_proto_legal_engine_proto_rawDesc = "" +
	"\n" +
	"\x18proto/legal_engine.proto\x12\flegal_engine\"\xe0\x01\n" +
	"\x06Clause\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x1f\n" +
	"\vclause_type\x18\x03 \x01(\tR\n" +
	"clauseType\x12\x1f\n" +
	"\vclause_text\x18\x04 \x01(\tR\n" +
	"clauseText\x12\x1d\n" +
	"\n" +
	"risk_level\x18\x05 \x01(\tR\triskLevel\x12%\n" +
	"\x0erisk_reasoning\x18\x06 \x01(\tR\rriskReasoning\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"M\n" +
	"\x16AnalyzeDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\xd2\x01\n" +
	"\x17AnalyzeDocumentResponse\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12.\n" +
	"\x13document_risk_level\x18\x02 \x01(\tR\x11documentRiskLevel\x126\n" +
	"\x17document_risk_reasoning\x18\x03 \x01(\tR\x15documentRiskReasoning\x12.\n" +
	"\aclauses\x18\x04 \x03(\v2\x14.legal_engine.ClauseR\aclauses\"4\n" +
	"\x11GetClausesRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\"D\n" +
	"\x12GetClausesResponse\x12.\n" +
	"\aclauses\x18\x01 \x03(\v2\x14.legal_engine.ClauseR\aclauses\"Q\n" +
	"\x16ExtractMandatesRequest\x12#\n" +
	"\rregulation_id\x18\x01 \x01(\tR\fregulationId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"5\n" +
	"\x17ExtractMandatesResponse\x12\x1a\n" +
	"\bmandates\x18\x01 \x03(\tR\bmandates\"\xa1\x01\n" +
	"\x14AnalyzeImpactRequest\x12!\n" +
	"\fmandate_text\x18\x01 \x01(\tR\vmandateText\x120\n" +
	"\x14internal_document_id\x18\x02 \x01(\tR\x12internalDocumentId\x124\n" +
	"\x16internal_document_text\x18\x03 \x01(\tR\x14internalDocumentText\"e\n" +
	"\x15AnalyzeImpactResponse\x12!\n" +
	"\fimpact_level\x18\x01 \x01(\tR\vimpactLevel\x12)\n" +
	"\x10impact_reasoning\x18\x02 \x01(\tR\x0fimpactReasoning2\x9b\x03\n" +
	"\x12LegalEngineService\x12^\n" +
	"\x0fAnalyzeDocument\x12$.legal_engine.AnalyzeDocumentRequest\x1a%.legal_engine.AnalyzeDocumentResponse\x12W\n" +
	"\x12GetDocumentClauses\x12\x1f.legal_engine.GetClausesRequest\x1a .legal_engine.GetClausesResponse\x12h\n" +
	"\x19ExtractRegulatoryMandates\x12$.legal_engine.ExtractMandatesRequest\x1a%.legal_engine.ExtractMandatesResponse\x12b\n" +
	"\x17AnalyzeRegulatoryImpact\x12\".legal_engine.AnalyzeImpactRequest\x1a#.legal_engine.AnalyzeImpactResponseB\x19Z\x17telis-api-gateway/pb;pbb\x06proto3"

var (
	file_proto_legal_engine_proto_rawDescOnce sync.Once
	file_proto_legal_engine_proto_rawDescData []byte
)

func file_proto_legal_engine_proto_rawDescGZIP() []byte {
	file_proto_legal_engine_proto_rawDescOnce.Do(func() {
		file_proto_legal_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_legal_engine_proto_rawDesc), len(file_proto_legal_engine_proto_rawDesc)))
	})
	return file_proto_legal_engine_proto_rawDescData
}

var file_proto_legal_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_legal_engine_proto_goTypes = []any{
	(*Clause)(nil),                  // 0: legal_engine.Clause
	(*AnalyzeDocumentRequest)(nil),  // 1: legal_engine.AnalyzeDocumentRequest
	(*AnalyzeDocumentResponse)(nil), // 2: legal_engine.AnalyzeDocumentResponse
	(*GetClausesRequest)(nil),       // 3: legal_engine.GetClausesRequest
	(*GetClausesResponse)(nil),      // 4: legal_engine.GetClausesResponse
	(*ExtractMandatesRequest)(nil),  // 5: legal_engine.ExtractMandatesRequest
	(*ExtractMandatesResponse)(nil), // 6: legal_engine.ExtractMandatesResponse
	(*AnalyzeImpactRequest)(nil),    // 7: legal_engine.AnalyzeImpactRequest
	(*AnalyzeImpactResponse)(nil),   // 8: legal_engine.AnalyzeImpactResponse
}
var file_proto_legal_engine_proto_depIdxs = []int32{
	0, // 0: legal_engine.AnalyzeDocumentResponse.clauses:type_name -> legal_engine.Clause
	0, // 1: legal_engine.GetClausesResponse.clauses:type_name -> legal_engine.Clause
	1, // 2: legal_engine.LegalEngineService.AnalyzeDocument:input_type -> legal_engine.AnalyzeDocumentRequest
	3, // 3: legal_engine.LegalEngineService.GetDocumentClauses:input_type -> legal_engine.GetClausesRequest
	5, // 4: legal_engine.LegalEngineService.ExtractRegulatoryMandates:input_type -> legal_engine.ExtractMandatesRequest
	7, // 5: legal_engine.LegalEngineService.AnalyzeRegulatoryImpact:input_type -> legal_engine.AnalyzeImpactRequest
	2, // 6: legal_engine.LegalEngineService.AnalyzeDocument:output_type -> legal_engine.AnalyzeDocumentResponse
	4, // 7: legal_engine.LegalEngineService.GetDocumentClauses:output_type -> legal_engine.GetClausesResponse
	6, // 8: legal_engine.LegalEngineService.ExtractRegulatoryMandates:output_type -> legal_engine.ExtractMandatesResponse
	8, // 9: legal_engine.LegalEngineService.AnalyzeRegulatoryImpact:output_type -> legal_engine.AnalyzeImpactResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_legal_engine_proto_init() }
func file_proto_legal_engine_proto_init() {
	if File_proto_legal_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_legal_engine_proto_rawDesc), len(file_proto_legal_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_legal_engine_proto_goTypes,
		DependencyIndexes: file_proto_legal_engine_proto_depIdxs,
		MessageInfos:      file_proto_legal_engine_proto_msgTypes,
	}.Build()
	File_proto_legal_engine_proto = out.File
	file_proto_legal_engine_proto_goTypes = nil
	file_proto_legal_engine_proto_depIdxs = nil
}
