// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/legal_engine.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LegalEngineService_AnalyzeDocument_FullMethodName    = "/legal_engine.LegalEngineService/AnalyzeDocument"
	LegalEngineService_GetDocumentClauses_FullMethodName = "/legal_engine.LegalEngineService/GetDocumentClauses"
)

// LegalEngineServiceClient is the client API for LegalEngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LegalEngineServiceClient interface {
	AnalyzeDocument(ctx context.Context, in *AnalyzeDocumentRequest, opts ...grpc.CallOption) (*AnalyzeDocumentResponse, error)
	GetDocumentClauses(ctx context.Context, in *GetClausesRequest, opts ...grpc.CallOption) (*GetClausesResponse, error)
}

type legalEngineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLegalEngineServiceClient(cc grpc.ClientConnInterface) LegalEngineServiceClient {
	return &legalEngineServiceClient{cc}
}

func (c *legalEngineServiceClient) AnalyzeDocument(ctx context.Context, in *AnalyzeDocumentRequest, opts ...grpc.CallOption) (*AnalyzeDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeDocumentResponse)
	err := c.cc.Invoke(ctx, LegalEngineService_AnalyzeDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *legalEngineServiceClient) GetDocumentClauses(ctx context.Context, in *GetClausesRequest, opts ...grpc.CallOption) (*GetClausesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClausesResponse)
	err := c.cc.Invoke(ctx, LegalEngineService_GetDocumentClauses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LegalEngineServiceServer is the server API for LegalEngineService service.
// All implementations must embed UnimplementedLegalEngineServiceServer
// for forward compatibility.
type LegalEngineServiceServer interface {
	AnalyzeDocument(context.Context, *AnalyzeDocumentRequest) (*AnalyzeDocumentResponse, error)
	GetDocumentClauses(context.Context, *GetClausesRequest) (*GetClausesResponse, error)
	mustEmbedUnimplementedLegalEngineServiceServer()
}

// UnimplementedLegalEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLegalEngineServiceServer struct{}

func (UnimplementedLegalEngineServiceServer) AnalyzeDocument(context.Context, *AnalyzeDocumentRequest) (*AnalyzeDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeDocument not implemented")
}
func (UnimplementedLegalEngineServiceServer) GetDocumentClauses(context.Context, *GetClausesRequest) (*GetClausesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDocumentClauses not implemented")
}
func (UnimplementedLegalEngineServiceServer) mustEmbedUnimplementedLegalEngineServiceServer() {}
func (UnimplementedLegalEngineServiceServer) testEmbeddedByValue()                            {}

// UnsafeLegalEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LegalEngineServiceServer will
// result in compilation errors.
type UnsafeLegalEngineServiceServer interface {
	mustEmbedUnimplementedLegalEngineServiceServer()
}

func RegisterLegalEngineServiceServer(s grpc.ServiceRegistrar, srv LegalEngineServiceServer) {
	// If the following call panics, it indicates UnimplementedLegalEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LegalEngineService_ServiceDesc, srv)
}

func _LegalEngineService_AnalyzeDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LegalEngineServiceServer).AnalyzeDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LegalEngineService_AnalyzeDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LegalEngineServiceServer).AnalyzeDocument(ctx, req.(*AnalyzeDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LegalEngineService_GetDocumentClauses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClausesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LegalEngineServiceServer).GetDocumentClauses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LegalEngineService_GetDocumentClauses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LegalEngineServiceServer).GetDocumentClauses(ctx, req.(*GetClausesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LegalEngineService_ServiceDesc is the grpc.ServiceDesc for LegalEngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LegalEngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "legal_engine.LegalEngineService",
	HandlerType: (*LegalEngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeDocument",
			Handler:    _LegalEngineService_AnalyzeDocument_Handler,
		},
		{
			MethodName: "GetDocumentClauses",
			Handler:    _LegalEngineService_GetDocumentClauses_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/legal_engine.proto",
}
